#!/usr/bin/env bash
# displays Best School 10 times.

COUNTER=1
while [ $COUNTER -lt 101 ]
do
	if [ $((COUNTER%3)) -eq 0 ] && [ $((COUNTER%5)) -eq 0 ]; then
        	echo "FizzBuzz"
    	elif [ $((COUNTER%3)) -eq 0 ]; then
        	echo "Fizz"
    	elif [ $((COUNTER%5)) -eq 0 ]; then
        	echo "Buzz"
    	else
        	echo "$COUNTER"
    	fi
    	 COUNTER+=1
done
