#!/usr/bin/env bash
# displays "Best School" 10 times using a while loop.
# on the 9th iteration, displays "Hi" and "Best School".
COUNTER=0
while [ $COUNTER -lt 11 ]
do
    if [ $COUNTER = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    let COUNTER+=1
done
